### ISSUE TITLE
Technic mod

### ISSUE THREAD

**Issue by farribeiro** [ronoaldo/mercurio#122]
Please, 

I suggest appreciation of the Technic mod. The mod in contentdb https://content.minetest.net/packages/RealBadAngel/technic/

Best regards
Fabio

**Comment by farribeiro** [comment]
Be careful that this mod has a nuclear reactor, which can make the server unusable if crafted wrong. only recover the server with invincibility and remove the radiation

**Comment by farribeiro** [comment]
btw... not forget to add the pipeworks mod

**Comment by jgoffredo** [comment]
Technic is a very good mod. Duplicate ores, has new ores. Compact machines. Electric furnaces etc.

The nuclear reactor may be a problem, but is very hard to get 3.5% uranium to use in reactors.

**Comment by ronoaldo** [comment]
Would both mods (Techpack and Technic) be usable together? I may add this one, and perhaps drop the nuclear reactor recipe.

**Comment by jgoffredo** [comment]
They (Techpack and Technic) can work together, but sometimes needs a chest to be used as interface.

Can implement in a test server before.

The nuclear reactor recipe can not be dropped, but the Nuclear Reactor Core can be. Without this the reactor can be build (almost, because is missing the core), but can not be turned on.

The player still can place radioactive blocks, but is not possible to make a nuclear disaster. And a world edit, or digging, can remove the radioactive block.

**Comment by jgoffredo** [comment]
All I tested in the test server worked fine.

**Comment by ronoaldo** [comment]
Adjusted the remaining settings and updated news. Merging soon.

**Comment by jgoffredo** [comment]
Two recipe problems happened.

Granite lost its recipe. Now can only be mined. Before Technic it was only got by crafting.

Aviation Device recipe changed to an almost impossible recipe, before it was a expensive recipe. Now I am the only player in server capable to make an Aviation Device, because it uses 3.5% Fissile Uranium, and I am the only player who has a Uranium possessing system.

Uranium processing system is very complicated and expensive. There is a less expensive version, but is very problematic.

**Comment by ronoaldo** [comment]
Thanks for the updates JGoffredo - Do you remember the previous recipe versions? I can add them back using the mercurio customization mod as I did for the mirthil items.

**Comment by jgoffredo** [comment]
This is one of granite recipes.

Tar and marble.

I "cheated" using microblock to use less material, because was one of recipes.

I think worked with tar panel and marble panel too.

![image](https://user-images.githubusercontent.com/19941797/221307516-182b840c-768f-44bd-98a1-8dcacf9af7c8.png)

I don't remember the Aviation Device recipe. I can´t find the mod in ContentDB. I think it used mese or diamond block instead Uranium. May be mese block. It was expensive, but not almost impossible.

I couldn't find the mod to verify.

**Comment by ronoaldo** [comment]
Will be fixed by #138
